### PR TITLE
handle various url types in redirects

### PR DESCRIPTION
**Pull request by ccorda**
To test.

Setup redirects for:
* /internal => /
* /internal/anchor => /#pledge
* /external => https://www.patronage.org

Using Curl, all of the following should work (once setup in WP):

curl -I https://bubs.patronage.org/internal
curl -I https://bubs.patronage.org/internal/
curl -I https://bubs.patronage.org/internal/anchor
curl -I https://bubs.patronage.org/internal/anchor/
curl -I https://bubs.patronage.org/external
curl -I https://bubs.patronage.org/external/

refs #153

### CODE REVIEW

**Comment by kylehotchkiss** [comment]
@ccorda is this ready for review?

**Comment by ccorda** [comment]
Yes please.

**Comment by kylehotchkiss** [comment]
Unexpected result on the first use case:

```
❯ curl -I http://localhost:3000/internal
HTTP/1.1 308 Permanent Redirect
Location: /internal/
Refresh: 0;url=/internal/
Date: Mon, 27 Sep 2021 20:16:10 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

```
❯ curl -I http://localhost:3000/internal/
HTTP/1.1 301 Moved Permanently
Location: 
Date: Mon, 27 Sep 2021 20:16:17 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by kylehotchkiss** [comment]
I resolved the issue I found earlier this week with `/internal` and will now merge this

**Pull request merged**
