### PR TITLE
OnRouteChange fix

### LINKED ISSUE #126: routeChangeComplete not correctly configured with useRouter
Currently routeChangeComplete event listener is not connected to the `useRouter()` hook: https://github.com/patronage/bubs-next/blob/main/website/src/pages/_app.js#L22-L34 

I found that it wasn't firing for me on page changes. I adjusted the syntax to follow the [`routeChangeComplete` syntax in Next docs](https://nextjs.org/docs/api-reference/next/router#usage-6) and then the page change events fired for me as expected. I don't understand why no error messages occurred with the current code configuration as this fails pretty silently. Since we've been using GTM which can track pageview events on its own, this wasn't showing in analytics data either.

### PR DESCRIPTION
**Pull request by kylehotchkiss**
closes #126

### CODE REVIEW

**Review by ccorda — CHANGES_REQUESTED** [review]
eslint error on returning the array as part of the hook:

> React Hook useEffect has a missing dependency: 'router.events'. Either include it or remove the dependency array.

Per next/examples PR, should be:
`[router.events]`

**Comment by kylehotchkiss** [comment]
The eslint error is one I often ignore, because in this case, `router.events` is a constant and will not change, therefore `[]` will work the same way as `[router.events]`. But because you flagged it, I googled it: https://betterprogramming.pub/stop-lying-to-react-about-missing-dependencies-10612e9aeeda

> As Abramov says:
> “Don’t lie to React about dependencies.”

I'll add it in but wish eslint did a better job determining whether the values it claims are dependencies are actually things that can change.

**Comment by kylehotchkiss** [comment]
@ccorda i added the eslint rule like we discussed last week. Is this one OK to merge now?

**Comment by ccorda** [comment]
Sure thing.

**Pull request merged**
