### PR TITLE
Disable gutenberg in functions.php

### LINKED ISSUE #266: Disable gutenberg w/o plugin
We can remove both the Gutenberg Ramp and Classic Editor plugins and replace with this line in `functions.php`

```php
// Disable Gutenberg Block Editor
add_filter('use_block_editor_for_post', '__return_false');
```

### PR DESCRIPTION
**Pull request by chrisherold**
fixes #266

### CODE REVIEW

**Comment by ccorda** [comment]
I'm down to remove the gutenberg ramp, but I'm not seeing this as an improvement over the official classic editor -- is there something this gets us that doesn't to see us change things? 

If we were to roll our own, then I think we'd need to have it be inside a dedicated helper file so we can easily update it by rsyncing in a new version, rather than having something hardcoded into the functions.php which is harder to update.

**Comment by chrisherold** [comment]
The classic editor is built into wordpress, the php just disables gutenberg so the classic editor is then the default. All the `classic editor` plugin does is block gutenberg globally and allow you to toggle back and forth between gutenberg and classic on individual pages.

**Comment by ccorda** [comment]
> Please note that this plugin is deprecated. The WordPress core filters should be used instead. See [here](https://developer.wordpress.org/reference/hooks/use_block_editor_for_post/).

I'm warming to the idea of this PR beyond simply removing plugins.

In particular because in Timber, we'll want to also remove the CSS:
https://smartwp.com/remove-gutenberg-css/

On the other hand, I do see us needing to support gutenberg in the future, especially as we look at Faust. I think the feedback I have here is to:

* Move this to a dedicated file, e.g. helpers/guternberg-disable.php so we can easily update in the future 
* In that file, have both the disabling of the editor, and removal of the css

**Comment by ccorda** [comment]
Implemented in #287

**Pull request closed without merging**
