### PR TITLE
feat: bumping husky to version 7

### PR DESCRIPTION
**Pull request by ccorda**
To test:

* pull
* `cd website`
* `yarn install`
* add junk to the top of a JS file
* go to commit it.

You should see the following, and you won't get to the commit stage.

```
yarn run v1.22.10
$ /Users/cameron/projects/bubs-next/website/node_modules/.bin/lint-staged
✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *.{js,jsx,ts,tsx}
    ✖ eslint --fix [FAILED]
  ↓ No staged files match *.{css,scss} [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...
```

### CODE REVIEW

**Comment by kylehotchkiss** [comment]
I get an error about file executable flags (I don't think we have our local git setup to track file flags). Can you try removing your repo, recloning, and seeing if you can replicate?

```
❯ git commit
hint: The 'website/.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
[53-husky 86866bb] test
 1 file changed, 4 insertions(+)

```

**Comment by ccorda** [comment]
Thanks Kyle. Tried on a totally fresh install, and now it works (successfully installing as executables as a part of the prepare step on first commit)

**Comment by ccorda** [comment]
@kylehotchkiss green now, can you review?

**Review by kylehotchkiss — APPROVED** [review]
just re-cloned and husky is now working as expected

**Pull request merged**
