### PR TITLE
Resolve WPEngine auto-updates

### LINKED ISSUE #128: WP Engine Auto Wordpress Updates failing
the `bubsnext` WP Engine install was pretty dated (wp 5.5 instead of 5.8) so I tried to update it from WP Engine dashboard. It fails pretty quickly after and emails this back to us:

> The specific failed test consists of checking your environment(s) before and after the update to ensure we receive a 200 (OK) response, which usually confirms that no fatal errors have occurred.
> As a result of the tests failing, we have reverted the following environment(s) to the previous version:

I then ran a backup of the install in WP Engine and proceeded to update the instance manually from the WP dashboard, where it succeeded immediately, with no errors on `/` or `/graphql`. I think we should resolve the WP engine auto updates for ease of site maintenance and to make sure we're not unintentionally blocking WP engine from applying security updates to sites.

I'm not sure which specific path WP Engine's updater verifies for the update test, but if it's `/`, maybe we could switch the redirect from being a HTTP status code to a html file with 200 response and meta redirect header - people aren't going to just  be stumbling upon the WP engine domain so this slower redirect doesn't seem to be a concern.

### PR DESCRIPTION
**Pull request by kylehotchkiss**
To demonstrate, checkout this branch and open wordpress in docker.

Default - redirect to vercel site
```
## Request
curl "http://localhost:8000/" -I
```

If WPEBot - return 200
```
## Request
curl "http://localhost:8000/" \
     -H 'User-Agent: Mozilla/5.0 (compatible; WPEBot)' -I

``` 

resolves #128

### CODE REVIEW

**Comment by kylehotchkiss** [comment]
These tests don't seem to be working in Curl but they are working in Paw. I'm going to deploy to a staging instance of wpengine that claims it needs an update to see if it works on wpengine

**Comment by kylehotchkiss** [comment]
It works on WPEngine! After deploying this code to staging site theme php template files, an actual wpengine wp version update worked as expected. This code just needs to be rolled out on every php template because `index.php` is not the template being used for `/` on some client sites.

**Comment by ccorda** [comment]
LGTM Kyle.

**Comment by kylehotchkiss** [comment]
@chrisherold for viz - for our existing projects, wpengine auto wp updates have been failing, by adding a small snippet to the top of the php files (whichever one that `/` would be using), wpengine auto updates can proceed

**Pull request merged**
