### PR TITLE
Wp init

### PR DESCRIPTION
**Pull request by ccorda**
This has our initial theme, both on the WP and next side of things

* [x] Get WP Engine deploy working as a part of subfolder/monorepo
* [x] Fetch data from WP graphql endpoint (local and production)
* [x] Render a basic page
* [x] Handle subpages 
* [ ] ~~Preview/fast refresh~~ (moved to #30)
* [x] Render posts (kyle)
* [x] Posts pagination (kyle)
* [x] Wordpress `headless` theme

refs #9
refs #5

### CODE REVIEW

**Comment by ccorda** [comment]
Testing:
Please note that Posts Per Page is an option in the code, and it's hardcoded to "1" to demonstrate the pagination works without making lots more Fyre Ipsum posts.

Posts Archive
 https://bubs-next-mecarpknh.vercel.app/posts
 Try the not-well-designed pagination above the footer
 https://bubs-next-mecarpknh.vercel.app/posts/page/1
 https://bubs-next-mecarpknh.vercel.app/posts/page/2
 https://bubs-next-mecarpknh.vercel.app/posts/fyre-ipsum
Categories Archive
 https://bubs-next-mecarpknh.vercel.app/categories/fyre-category
 https://bubs-next-mecarpknh.vercel.app/categories/fyre-category/page/1
Tags Archive
 https://bubs-next-mecarpknh.vercel.app/tags/fyre-tag/
 https://bubs-next-mecarpknh.vercel.app/tags/fyre-tag/page/1

**Comment by ccorda** [comment]
@kylehotchkiss sorry about the inadvertent premature merge.

After testing things worked as intended, though one note on URL structure, to more closely match WP ([sample](https://www.accountable.us/news/)), can we do it like this

* `/posts/category/${slug}`
* `/posts/tag/${slug}`

**Comment by kylehotchkiss** [comment]
@ccorda thankfully that was as easy as just moving the folders. New paths:

### Categories Archive

* [ ] https://bubs-next-mecarpknh.vercel.app/posts/categories/fyre-category
* [ ] https://bubs-next-mecarpknh.vercel.app/posts/categories/fyre-category/page/1

### Tags Archive

* [ ] https://bubs-next-mecarpknh.vercel.app/posts/tags/fyre-tag/
* [ ] https://bubs-next-mecarpknh.vercel.app/posts/tags/fyre-tag/page/1

**Comment by ccorda** [comment]
in WP, it's `category` and `tag`, not `categories` or `tags`. Last thing from me, then I think we should merge this PR.

**Comment by kylehotchkiss** [comment]
@ccorda i made the final change for /post/category /post/tag, let's get this merged

**Pull request merged**
