### PR TITLE
refactor: Making redirects DRY, expire graphcdn on edit

### LINKED ISSUE #170: Redirection: Clear graphcdn on creation or removal of a redirect
If a redirect is created or changed, we should clear graphcdn global, otherwise we're gonna have some stale data:

https://redirection.me/developer/wordpress-hooks/

> redirection_remove_existing – fired when a post changes permalink and we need to clear existing redirects that might affect it

### LINKED ISSUE #171: Redirection: Monitor pages by default
When published pages or posts change urls, it's a nice feature to monitor for those and redirect for end-users.

Redirection has support for this, and they also have the ability to set configuration in code, so we should be able to do this by default:

https://github.com/johngodley/redirection/blob/50aaa1c774117086c10083c7c03fe3aea25efa30/redirection-settings.php#L44

### LINKED ISSUE #186: Redirect Bugs
Was just implementing a Yoast (premium) version of redirects, and I noticed a few bugs:

* Our absolute check doesn't make sense to me right now as written:

```
     if (
        redirect.target.indexOf('http://') > 0 ||
        redirect.target.indexOf('http://')
      )
```

* We currently check: `statusCode: redirect.code || 307,` -- but in our graphql, we normalize to `redirect.statusCode`

* ~~Our redirects are limited to whatever the WP limit is, which can be only 100 (and sometimes there are more than 100)~~ edit: this is actually ignored, all are returned.

* If we have a site with multiple paths, we're not checking subfolder paths for any redirects that may exist there.

### PR DESCRIPTION
**Pull request by ccorda**
closes #186 
closes #171
closes #170 

need to make sure we haven't backslid on #153.

To make code more DRY, this might be a place where we add a checkRedirects file to lib, and it'd be a great candidate for some tests and being part of a future npm packaged release.

* [x] logic works for both redirection and yoast premium
* [x] works with https, http, relative, and anchor links
* [x] DRY code usable in more than one top level file
* [x] works with more than 100 redirects
* [x] clears graphcdn on saving of a redirect
* [ ] ~~monitor for changes enabled by default~~

### CODE REVIEW

**Comment by ccorda** [comment]
Sample links to test out:

curl -I https://bubs-next-git-186-redirects-patronage.vercel.app/external/
curl -I https://bubs-next-git-186-redirects-patronage.vercel.app/internal/anchor/
curl -I https://bubs-next-git-186-redirects-patronage.vercel.app/internal/
curl -I https://bubs-next-git-186-redirects-patronage.vercel.app/posts/kitchen-sink/

**Comment by ccorda** [comment]
Ready for review.

My goal here was to make things more DRY, so that redirects can be extended to child templates more easily (see kitchen sink sample url).

Also enabled graphcdn expiration so that when you change a shortcut, it clears cache there (for now it's still purge all, but we'll get more nuanced soon). To make upgrading easier, I moved all webhooks configuration to the top level `functions.php`. This should let us simply over-right webhooks.php in the future, or eventually move to something from a package manager.

curl -I https://bubs-next-git-186-redirects-patronage.vercel.app/external/
curl -I https://bubs-next-git-186-redirects-patronage.vercel.app/internal/anchor/
curl -I https://bubs-next-git-186-redirects-patronage.vercel.app/internal/
curl -I https://bubs-next-git-186-redirects-patronage.vercel.app/posts/kitchen-sink/

**Comment by kylehotchkiss** [comment]
testing note, third redirect above just goes to `/`

```
❯ curl -I https://bubs-next-git-186-redirects-patronage.vercel.app/internal/
HTTP/2 307 
x-robots-tag: noindex
x-matched-path: /[[...slug]]
cache-control: public, max-age=0, must-revalidate
content-length: 0
location: /
date: Tue, 28 Dec 2021 00:05:39 GMT
x-vercel-cache: STALE
age: 77156
server: Vercel
x-vercel-id: sfo1::sfo1::xh9t5-1640727095862-fd47ec9f86b3
strict-transport-security: max-age=63072000; includeSubDomains; preload
```

if that was the intension, all tests pass for me

**Review by kylehotchkiss — APPROVED** [review]
code LGTM, appreciate the DRY / more consistent variable naming for headless config

**Comment by ccorda** [comment]
Thanks @kylehotchkiss. Confirmed that is intended behavior on `/internal`.

**Pull request merged**
